Refactored get distribution

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# by robert Plestenjak, robert.plestenjak@xlab.si
+# by Robert Plestenjak, robert.plestenjak@xlab.si
 # by Stanislav Petr, glux@glux.org
 #
 # depends on: cloud-utils
@@ -60,27 +60,72 @@ function copy-tools() {
   done <${inst_dir}/distro/${distro}/deps
 }
 
-function initrd() {
-  # clean up
-  [ -d /tmp/initrd ] && rm -rf /tmp/initrd
-  # create temp directory and move there
-  mkdir /tmp/initrd && cd /tmp/initrd
-  # extract current initrd
-  gunzip -c ${initrd} | cpio -i --make-directories
-  # modify
-  copy-tools
+gziped-initrd() {
+  file ${initrd} | grep -q gzip
+  return $(expr 1 - $?)
+}
+
+unpack-initrd() {
+  # check format of current initrd and extract it
+  if gziped-initrd; then
+        #echo "dracut"
+		execute=$(/usr/lib/dracut/skipcpio ${initrd} | gunzip -c | cpio -i -d && echo )
+  else
+	execute=$(gunzip -c ${initrd} | cpio -i --make-directories)
+  fi
+}
+
+repack-initrd() {
+  find ./ | cpio -H newc -o > /tmp/initrd.cpio
+  if gziped-initrd; then
+    gzip -c /tmp/initrd.cpio > ${initrd%-*}mod-${initrd##*-}
+  else
+    cp /tmp/initrd.cpio ${initrd%-*}mod-${initrd##*-}
+  fi
+}
+
+is-initrd-systemd() {
+  [ -x "${init_script}" ] && file "${init_script}" | grep -q "GNU/Linux"
+  return $?
+}
+
+modify-initrd-systemv() {
   touch etc/mtab
   [ "${mod_type}" == "mod_lvm" ] && \
     sed -i "s/locking_type = 4/locking_type = 1/" etc/lvm/lvm.conf
   mod_file=${inst_dir}/distro/${distro}/${mod_type}
   sed -i -e "/${proc_insert_point}/r ${mod_file}" -e "//N" ${init_script}
   sed -i "/${call_insert_point}/i ${proc_name}" ${init_script}
+}
+
+modify-initrd-systemd() {
+  local mod_file=${inst_dir}/distro/${distro}/${mod_type}
+  cp ${inst_dir}/systemd-growroot.service usr/lib/systemd/system/systemd-growroot.service
+  ln -s usr/lib/systemd/system/systemd-growroot.service usr/lib/systemd/system/sysinit.target.wants/systemd-growroot.service
+  cat $mod_file > bin/auto-growroot
+  echo growroot >> bin/auto-growroot
+  chmod +x bin/auto-growroot
+}
+
+initrd() {
+  # clean up
+  [ -d /tmp/initrd ] && rm -rf /tmp/initrd
+  # create temp directory and move there
+  mkdir /tmp/initrd && cd /tmp/initrd
+  # extract current initrd
+  unpack-initrd
+  # modify
+  copy-tools
+  if is-initrd-systemd; then
+    modify-initrd-systemd
+  else
+    modify-initrd-systemv
+  fi
   # create new
-  find ./ | cpio -H newc -o > /tmp/initrd.cpio
-  gzip -c /tmp/initrd.cpio > ${initrd%-*}mod-${initrd##*-}
+  repack-initrd
   # clean up
   cd ${inst_dir}
-  rm -rf /tmp/initrd.cpio /tmp/initrd
+  # rm -rf /tmp/initrd.cpio /tmp/initrd
 }
 
 function grub-mod() {
@@ -173,7 +218,7 @@ function main() {
   # set common variables
   partition-type
   [ $? -eq 1 ] && mod_type="mod_lvm" || mod_type="mod"
-
+}
   # check distro and set distro specific variables
   distro=$(get-distro)
 
@@ -246,8 +291,6 @@ else
   	echo "Distribution NOT supported!"
 exit 1  
 fi
-
-
 
 initrd
 grub-mod ${grub}
